services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - oil_tracker_db_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    command: >
      postgres
      -c shared_buffers=512MB
      -c max_connections=50
      -c work_mem=16MB

  scraper:
    build: .
    restart: always
    command: python src/tracker/main.py
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - TZ=America/New_York
      - PYTHONPATH=/app
    depends_on:
      - db
  api:
    build: .
    restart: always
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app/src
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - TZ=America/New_York
      - PYTHONPATH=/app
    depends_on:
      - db
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_ADDRESS=projects.alexmroberts.net
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src/portal:/var/www/portal
      - caddy_data:/data
      - caddy_config:/config
  oil-dashboard:
    build: .
    command: streamlit run src/ui/dashboard.py --server.port 8501 --server.address 0.0.0.0 --browser.gatherUsageStats false
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - API_URL=http://api:8000/prices
      - FAVICON_URL=https://alexmroberts.net/assets/images/favicon.png
    restart: always
volumes:
  caddy_data:
  caddy_config:
  oil_tracker_db_data: